server:
  port: 8090
  address: 0.0.0.0
spring:
  application:
    name: chatbot-api
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


chatbot-api:
  #openAI配置
  openai:
    modol: ${OPENAI_MODEL:text-davinci-003}
    apiKey: ${OPENAI_API_KEY:你的 OPENAI_API_KEY}
  #知识星球配置
  zsxq:
    cookie: ${ZSXQ_COOKIE:你的 COOKIE}}
    groupId: ${ZSXQ_GROUP_ID:28885518425541}
    groupName: ${ZSXQ_GROUP_NAME:ChatGPT AI 问答助手}
    # 是否提醒提问者
    silenced: ${ZSXQ_SILENCED:true}
  #任务配置
  task:
    #并发
    concurrent:
      #默认关闭（串行）
      enable: false
      # 并发大小（不填则等同于任务数，即全并发）
      size: 1
    list:
      - name: chatbot-api #任务名
        monitor: zsxq #监控者
        answer: openai #回答者
        cron: '0/30 * * * * ? ' #时间表达式


knife4j:
  enable: true
  openapi:
    title: chatbot-api开放平台api
    description: 这里有该平台所有开放接口供大家测试
    email: heposay@qq.com
    concat: 林海波
    url: https://github.com/heposay/chatbot-api.git
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      dev:
        group-name: 开发环境
        api-rule: package
        api-rule-resources:
          - cn.heposay.ai.controller

